version: '3.8'  # You can adjust the version if needed

services:
  postgres:
    image: postgres:latest
    container_name: notes_db
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
